language: node_js
node_js:
  - "6"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - npm run build.prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 'f41a2b44502ff0571207ce9725c61dda54ecbd7d '
  local_dir: dist
  on:
    branch: master
